apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: k8s-workshop-api
    port: 8080
    targetPort: 8080
    nodePort: 31234